version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: webtask
      MYSQL_USER: lamp_demo
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      # docker-php-ext-install mysqli
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: php:8.1.1-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
        # command: "docker-php-ext-install mysqli"
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge